# Generated by Django 4.2 on 2025-04-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('caracteristicas', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Verificada', 'Verificada'), ('En proceso', 'En proceso')], max_length=20)),
            ],
        ),
    ]
