# Generated by Django 4.2 on 2025-04-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
