# Generated by Django 4.2 on 2025-04-30 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('duracion_total', models.IntegerField(help_text='Duración en días')),
                ('dias_mejora', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('No vigente', 'No vigente')], max_length=20)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_enfermedades.enfermedad')),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
